# Github
general_repo: "https://github.com/realmaacke/General.git"

# Devusername
start_user: devuser

# ssh access
authorized_users_groups:
  - devuser
  - normal_user
# Startup users to be created
users_init:
  - user: marcus
    password: "{{ marcus_password }}" # Vault stored
    groups:
      - sudo

  - user: devuser
    password: "{{ devuser_password }}" # Vault stored
    groups:
      - sudo

  - user: superuser
    password: "password"
    groups:
      - sudo

first_init_development_groups:
  - sudo