---
ports:
  - { name: GRAFANA_PORT, port: 3000 }
  - { name: MARIADB_PORT, port: 3306 }
  - { name: DASHBOARD_PORT, port: 5173 }
  - { name: OVERSEER_PORT, port: 5055 }
  - { name: RADARR_PORT, port: 7878 }
  - { name: TRANSMISSION_PORT, port: 7978 }
  - { name: API_PORT, port: 8086 }
  - { name: SONARR_PORT, port: 8989 }
  - { name: SEARCH_PORT, port: 7777 }
  - { name: PROMETHEUS_PORT, port: 9090 }
  - { name: TV_PORT, port: 9092 }
  - { name: CDN_PORT, port: 9093 }
  - { name: DISCORD_PORT, port: 9094 }
  - { name: POSTGRES_PORT, port: 9098 }
  - { name: SONAR_PORT, port: 9099 }
  - { name: NODE_EXPORTER, port: 9100 }
  - { name: PORTTRAINER, port: 9101 }
  - { name: JACKETT_PORT, port: 9117 }
  - { name: PLEX_PORT, port: 32400 }
  - { name: PHPMYADMIN_PORT, port: 8081 }
  - { name: NGINX_HTTP_PORT, port: 80 }
  - { name: NGINX_HTTPS_PORT, port: 443 }

settings:
  - { name: PROJECT_ROOT, value: "/home/{{ start_user }}/dev/general"}
  - { name: START, value: "/home/{{ start_user }}"}

  - { name: MARIADB_HOST, value: mariadb }
  - { name: MARIADB_ROOT_PASSWORD, value: supersecret }
  - { name: MARIADB_DATABASE, value: general }
  - { name: MARIADB_USER, value: general_admin }
  - { name: MARIADB_PASSWORD, value: general_pass }

  - { name: OPENVPN_USERNAME, value: "{{ open_vpn_username }}"}
  - { name: VPN_USERNAME, value: "{{ open_vpn_username }}"}
  - { name: OPENVPN_PASSWORD, value: "{{ open_vpn_password }}"}
  - { name: VPN_PASSWORD, value: "{{ open_vpn_password }}"}
  - { name: OPENVPN_CONFIG, value: Sweden}