---
- name: Add rules to ufw
  community.general.ufw:
    rule: "{{ item.rule }}"
    name: "{{ item.name | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
  loop: "{{ ufw_rules }}"

- name: Ensure ufw is enabled
  community.general.ufw:
    state: enabled
