---
- name: Create database structure (1/3)
  ansible.builtin.command: mkdir -p /home/{{start_user}}/dev/general/database/init

- name: Create database structure (2/3)
  ansible.builtin.command: mkdir -p /home/{{start_user}}/dev/general/database/data

- name: Create database structure (3/3)
  ansible.builtin.command: mkdir -p /home/{{start_user}}/dev/general/database/logs